[package]
name = "rusty-raytracer"
version = "0.1.0"
authors = ["Michael Koegeboehn <50760114+mkoegeboehn@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
num = "0.4.0"
